# Generated by Django 5.1 on 2025-07-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the user.', max_length=100)),
                ('email', models.EmailField(help_text='Unique email address of the user.', max_length=254, unique=True)),
                ('github', models.URLField(blank=True, help_text="URL to the user's GitHub profile.", null=True)),
                ('leetcode', models.URLField(blank=True, help_text="URL to the user's LeetCode profile.", null=True)),
                ('codeforces', models.URLField(blank=True, help_text="URL to the user's Codeforces profile.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the profile was created.')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
